# Generated by Django 2.2.5 on 2019-09-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='languages',
            new_name='language',
        ),
    ]
