# Generated by Django 2.2.5 on 2019-09-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_cast_movielinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(related_name='movie_cast', to='movie.Movie'),
        ),
    ]
