# Generated by Django 2.2.5 on 2019-09-13 02:52

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('movie', '0004_auto_20190913_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
