# Generated by Django 2.2.5 on 2019-09-13 04:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190913_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance')], max_length=4),
        ),
    ]
