# Generated by Django 2.2.5 on 2019-09-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20190913_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('GE', 'German')], max_length=7),
        ),
    ]
