# Generated by Django 2.2.5 on 2019-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20190913_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
