# Generated by Django 2.2.5 on 2019-09-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20190913_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(default='', upload_to='movies/banners/'),
            preserve_default=False,
        ),
    ]
