# Generated by Django 2.2.5 on 2019-09-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_movie_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
