# Generated by Django 2.2.5 on 2019-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20190914_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
